# Generated by Django 3.2.5 on 2022-08-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_question_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answear',
            name='slug',
        ),
    ]
