# Generated by Django 3.2.5 on 2022-08-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_answear_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answear',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answear',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answear',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
