# Generated by Django 3.2.5 on 2022-10-26 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20220810_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
