# Generated by Django 3.2.5 on 2022-10-26 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
