# Generated by Django 3.2.5 on 2022-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_question_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
