# Generated by Django 3.2.5 on 2022-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_answer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='drawing',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
